### ISSUE TITLE
Regarding unable to load skull dataset locally

### ISSUE THREAD

**Issue by mmmovania** [Twinklebear/webgpu-prog-iso#1]
Thanks for sharing your work. i was trying to run the code locally. i was able to setup my environment on my Windows machine. When I try to run it, the app launches and shows some garbage memory data as shown below
![image](https://github.com/user-attachments/assets/216bb91a-e99d-4f8a-932c-22b43d7a3826)

This is likely because the dataset is not accessible and upon inspecting the console. I see this error
```
:5500/models/skull_256x256x256_uint8.raw.crate2.zfp:1 
Failed to load resource: the server responded with a status of 404 (Not Found)

``` 

which shows the dataset is not accessible. In your demos you are using cdn to access the data but that too is not accessible for me. I know i can download the raw volumes from the OpenSiVis website but can you please share how to convert these datasets to zfp format that is needed by the app?

**Comment by mmmovania** [comment]
Nevermind, i just saw you have another repo: https://github.com/Twinklebear/webgpu-bcmc-data-generator

**Comment by Twinklebear** [comment]
Hi @mmmovania , yes the data files are a bit large so I didn't include them in the repo or with git LFS. You can download the test datasets from the paper + a few extras here: https://drive.google.com/file/d/1079_R_lTcdHCcY4TrQCjpaKVO3fzx1Yu/view?usp=sharing
